### ISSUE TITLE
[Feature] Change the issue template to the new style

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Lilliputian-Bot#11]
### Is your feature request related to a problem? Please describe.
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

### Describe the solution you'd like
**A clear and concise description of what you want to happen.**

### Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**

### Additional context
**Add any other context or screenshots about the feature request here.**

**Comment by kaiwalyakoparkar** [comment]
@Cahllagerfeld Would you be able to help here. I am a bit confused about the yaml syntax. I want to change all the issue and PR templates to the new form structure.

**Comment by indevi** [comment]
@kaiwalyakoparkar May I help with this good first issue?

**Comment by kaiwalyakoparkar** [comment]
@ShivamTyagi12345 why not! Go ahead, I will assign this to you :smile:
