### ISSUE TITLE
[Bug] React to get roll feature does not work

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Lilliputian-Bot#19]
### Describe the bug
**A clear and concise description of what the bug is :**

### To Reproduce
**Steps to reproduce the behavior:**

### Expected behavior
**A clear and concise description of what you expected to happen.**

### Screenshots/ Video
**If applicable, add screenshots to help explain your problem.**

### Additional context
**Add any other context about the problem here.**

**Comment by Cahllagerfeld** [comment]
In `roleClaim.js` is a [hardcoded](https://github.com/kaiwalyakoparkar/Lilliputian-Bot/blob/1c5369991ce8f23769b05872827d926b5690a615/Commands/roleClaim.js#L23) UserID. Which UserID is that?

**Comment by kaiwalyakoparkar** [comment]
It's the role ID, It's single server setting as of now :)
