### ISSUE TITLE
[Bug] Broken link in README.md

### ISSUE THREAD

**Issue by verma-kunal** [kaiwalyakoparkar/Lilliputian-Bot#22]
The **Sponser** link in the `readme.md` file is broken and doesn't redirect to the specific page.

Screenshot: 
![Screenshot 2021-07-09 at 11 50 00 AM](https://user-images.githubusercontent.com/72245772/125032574-cbe8e780-e0ab-11eb-8fa4-b0ad594080b6.png)

**Comment by kaiwalyakoparkar** [comment]
@verma-kunal Hey thanks for raising that issue. The link is correct but I haven't set up the sponsorships yet so is deactivated for time being. As soon as I set that up it will be activated automatically. :)

**Comment by kaiwalyakoparkar** [comment]
I will keep this issue open as it will keep me nudging to set it up asap

**Comment by verma-kunal** [comment]
Oh! alright, no worries 🙂
