### ISSUE TITLE
[Bug] Get Version from env

### ISSUE THREAD

**Issue by Cahllagerfeld** [kaiwalyakoparkar/Lilliputian-Bot#24]
### Describe the bug
**A clear and concise description of what the bug is :**
[currently](https://github.com/kaiwalyakoparkar/Lilliputian-Bot/blob/2598c525debce9d0629a124bbdee2feb37f740bb/Commands/version.js#L2) you require your packe.json to get the version number

### Additional context
**Add any other context about the problem here.**
You could use `process.env.npm_package_version` or see the docs from npm [here](https://docs.npmjs.com/cli/v6/using-npm/scripts#packagejson-vars)

**Comment by kaiwalyakoparkar** [comment]
Oh! Nice idea actually. Let's try this out
