### ISSUE TITLE
[Bug] Hardcoded ChannelID

### ISSUE THREAD

**Issue by Cahllagerfeld** [kaiwalyakoparkar/Lilliputian-Bot#25]
### Describe the bug
**A clear and concise description of what the bug is :**
Theres a channelID hardcoded (see [here](https://github.com/kaiwalyakoparkar/Lilliputian-Bot/blob/2598c525debce9d0629a124bbdee2feb37f740bb/Commands/roleClaim.js#L4)). I'm not that deep into discord.js but will this feature still work when somebody invites the bot to a custom server?

**Comment by kaiwalyakoparkar** [comment]
Hmmm :thinking: I am trying to integrate MongoDB for this purpose would you like to help on that?
