### ISSUE TITLE
[Feature] Special category message should be available.

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Lilliputian-Bot#28]
Say suppose if a channel was created for sharing job opportunities. People tend to send irrelevant or spammy messages there (by mistake also) So the task is to build a system that will check specific keywords in a message like in this case [internship, job, intern], etc. If the message contains the keywords then only it will be sent to the channel else will be deleted. 
This will confirm the purpose of the channel.

**Comment by AbhijithGanesh** [comment]
So I think for this we need to compile the set of words relevant to job opportunities, like Job, Opening, Availability, Vacancy, etc. 
Can I work on this please?
